version: '3.8'
services:
  jenkins:
    image: jenkins/jenkins:lts-jdk21
    container_name: jenkins
    networks:
        - jenkins-network
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins-data:/var/jenkins_home
      - var/run/docker.sock:/var/run/docker.sock
      - $(which docker):/usr/bin/docker

    restart: unless-stopped
    group_add:
      - $(stat -c '%g' /var/run/docker.sock)

volumes:
  jenkins-data:
  
networks:
  jenkins-network:
